### ISSUE TITLE
自己紹介文章にHTMLを使うとXSS状態になる

### ISSUE THREAD

**Issue by windyakin** [ysakasin/proconist.net#36]
自己紹介文章になんの気なしでHTMLタグを挿入したのですが，OGPの部分でサニタイズされていないのでXSS的な感じになっています。

https://proconist.net/auther/windyakin

``` html
  <meta property="og:description" content="津山高専 専攻科2年生 🐘 「デザイン方針の決定」という謎の役割を担当 ✋ I <i class="fa fa-heart"></i> <i class="fa fa-tumblr"></i>">
```

自己紹介文章にHTMLを使えないようにするか，OGPの部分でタグを削除するかした方がいいかと思います。(私が自己紹介文章にHTMLを使わなければいいだけ)

**Comment by NKMR6194** [comment]
XSS対策はあえてしてませんでした。アカウントを持っている人はある程度知り合いな特定少数なので問題ないかなと思っています
fontawesomeとか使えた方が楽しいですし！

**Comment by NKMR6194** [comment]
しかし、おっしゃる通り心配な部分もあるので、管理権限を持つユーザーが各ユーザーの自己紹介文の生テキストを確認/編集できるようにはしようと思います。

**Comment by ysakasin** [comment]
#75 で `/author` は廃止になった
