### ISSUE TITLE
Webコンソールからリポジトリ情報を削除できない

### ISSUE THREAD

**Issue by ysakasin** [ysakasin/proconist.net#61]
`https://proconist.net/console/entrant/XXX` で過去に入力されていたリポジトリのURLを空欄にして保存しても、空欄にしたリポジトリの情報が削除されない。

**Comment by unasuke** [comment]
😨

**Comment by NKMR6194** [comment]
問題が発生した実データは、応急処置としてSQL叩いて直した。Bugが治るまでの間は、データ修正の際に気をつける。

**Comment by ysakasin** [comment]
#75 でMIddleman移行をしたため解消
