### ISSUE TITLE
情報提供の通知メールがGmailで迷惑メールに分類される

### ISSUE THREAD

**Issue by ysakasin** [ysakasin/proconist.net#64]
```
このメールが [迷惑メール] に振り分けられた理由: Google が推奨するメール送信者のガイドラインに違反しています。
```
[一括送信ガイドライン](https://support.google.com/mail/answer/81126?hl=ja#authentication)

```
From: | noreply@proconist.net
-- | --
To: | [hoge]
日付: | 2017年10月10日 7:44
件名: | 情報提供がありました
セキュリティ: | このメールは sakura.ne.jp で暗号化されませんでした 詳細
```

詳細 → https://support.google.com/mail/answer/6330403?visit_id=1-636434801550372854-3088776936&p=tls&hl=ja&rd=1

このドメインからのメールを受信する人は相当限られるはずなので、優先度は低で。

**Comment by NKMR6194** [comment]
適切にDNSのMXレコードを追加すれば大丈夫な気がする

http://plusblog.jp/8842/

**Comment by unasuke** [comment]
👀

**Comment by ysakasin** [comment]
#75 でGoogle Formに移行
